apiVersion: apps/v1
kind: Deployment
metadata:
  name: eclipse-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eclipse-app
  template:
    metadata:
      labels:
        app: eclipse-app
    spec:
      containers:
        - name: eclipse-container
          image: ashish2705/eleven:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: eclipse-app-service
spec:
  selector:
    app: eclipse-app
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer